name: BountyHunt
version: 1.0.0
main: com.jinzo.BountyHunt
api-version: 1.16
folia-supported: true

commands:
  bounty:
    description: Bounty system
    usage: /bounty <set|check|top|remove>

permissions:
  bountyhunt.bounty:
    description: Base permission for the bounty command
    default: true
  bountyhunt.bounty.set:
    description: Allows placing bounties
    default: true
  bountyhunt.bounty.check:
    description: Allows checking bounty on players
    default: true
  bountyhunt.bounty.top:
    description: Allows viewing top bounties
    default: true
  bountyhunt.bounty.remove:
    description: Allows a player to remove a bounty
    default: op
