name: BountyHunt
version: 0.0.1-SNAPSHOT
main: com.jinzo.BountyHunt
api-version: 1.16
folia-supported: true

commands:
  bounty:
    description: Place a bounty on a player
    usage: /bounty <player> <amount>
    permission: bountyhunt.bounty
    permission-message: You do not have permission to use this command.
  bountytop:
    description: View the top bounties
    usage: /bountytop
    permission: bountyhunt.bountytop
    permission-message: You do not have permission to view top bounties.
  bountycheck:
    description: Check your current bounties
    usage: /bountycheck <player>
    permission: bountyhunt.bountycheck
    permission-message: You do not have permission to check bounties.
  bountyclaim:
    description: Claim your earned bounty rewards
    usage: /bountyclaim
    permission: bountyhunt.bountyclaim
    permission-message: You do not have permission to claim bounties.

permissions:
  bountyhunt.bounty:
    description: Allows the player to place bounties
    default: true
  bountyhunt.bountytop:
    description: Allows the player to view top bounties
    default: true
  bountyhunt.bountycheck:
    description: Allows the player to check a player’s bounty
    default: true
  bountyhunt.bountyclaim:
    description: Allows the player to claim earned bounties
    default: true