name: BountyHunt
version: 0.0.1-SNAPSHOT
main: com.jinzo.BountyHunt
api-version: 1.16
folia-supported: true

commands:
  bounty:
    description: Bounty system
    usage: /bounty <set|check|top>
    permission: bountyhunt.bounty
    permission-message: You do not have permission to use bounty commands.

permissions:
  bountyhunt.bounty.set:
    description: Allows placing bounties
    default: true
  bountyhunt.bounty.check:
    description: Allows checking bounty on players
    default: true
  bountyhunt.bounty.top:
    description: Allows viewing top bounties
    default: true
